config/routes.rb
InstagramApp::Application.routes.draw do

  get :callback, to: 'welcome#callback'
  get :authenticate, to: 'welcome#authenticate'
  get :logout, to: 'welcome#logout'

  scope '/sts' do
    scope '/v1' do
      scope '/api' do
        resources :stories, only: [:index], :controller => "api_stories"
      end
    end
  end

  scope '/sts-admin' do
    get '/'  => 'admin#index'
    scope '/api' do
      resources :stories, only: [:index], :controller => "api_admin_stories"
    end
  end

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commentable_id, :commentable_type, :liked_count, :user_id
  belongs_to :commentable, :polymorphic => true
  has_ancestry
end

app/models/seed.rb
class Seed

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :headline, :status, :url, :user_id, :publish_date
  has_many :comments, :as => :commentable
  belongs_to :user

  def self.by_date date_val
    Story.where('publish_date=?', date_val)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :auth_token, :full_name, :instagram_id, :user_name
  has_many :stories


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/api_admin_stories_controller.rb
class ApiAdminStoriesController < ApplicationController
  before_filter :authenticate_user!, only: [:logout]

  def index
     @stories=Story.all
     render json: @stories.to_json
  end
end

app/controllers/api_stories_controller.rb
class ApiStoriesController < ApplicationController
  before_filter :authenticate_user!, only: [:logout]

  def index
    date0=Date.today-0
    @stories0=Story.by_date(date0)
    d={}
    d[:date]=date0
    d[:stories]=ActiveModel::ArraySerializer.new(@stories0, each_serializer: StorySerializer)

    date1=Date.today-1
    @stories1=Story.by_date(date1)
    e={}
    e[:date]=date1
    e[:stories]=ActiveModel::ArraySerializer.new(@stories1, each_serializer: StorySerializer)

    date2=Date.today-2
    @stories2=Story.by_date(date2)
    f={}
    f[:date]=date2
    f[:stories]=ActiveModel::ArraySerializer.new(@stories2, each_serializer: StorySerializer)

    #r[date2]=ActiveModel::ArraySerializer.new(@stories2, each_serializer: StorySerializer)
    r=[d,e,f]

    date3=Date.today-3
    date4=Date.today-4
    date5=Date.today-5
    date6=Date.today-6

    #@stories=Story.all
    #render json: @stories, each_serializer: StorySerializer, root: false
    render json: r.to_json
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_user!
    unless session[:instagram_id] && current_user
      flash[:error] = "Access Denied, Please sign in"
      redirect_to root_url
    end
  end

  def current_user
    User.find_by_instagram_id(session[:instagram_id])
  end

  helper_method :current_user
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, only: [:logout]

  def index
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => callback_url)
    #binding.pry
    if response
      user = User.find_by_instagram_id(response.user.id)
      if user
        user.update_attributes(auth_token: response.access_token, user_name: response.user.username, full_name: response.user.full_name, instagram_id: response.user.id)
      else
        User.create(auth_token: response.access_token, user_name: response.user.username, full_name: response.user.full_name, instagram_id: response.user.id)
      end
    end
    session[:instagram_id] = response.user.id
    session[:user_image] =response.user.profile_picture
    redirect_to root_url
  end

  def authenticate
    redirect_to Instagram.authorize_url(:redirect_uri => callback_url)
  end

  def logout
    session[:instagram_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<script src='/js/admin-1431.js'></script>
within index
<div class='submitted-stories'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "InstagramApp" %></title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0/handlebars.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">InstagramApp</a>
          <div class="container nav-collapse navbar-right">
            <ul class="nav">
              <%#binding.pry%>
              <% if current_user %>
                <li><%= link_to "Logout", logout_path  %></li>
              <% else %>
                <li><%= link_to "Login", authenticate_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:error].present? %>
      <div class="row alert alert-danger">
      <%=flash[:error] %>
      </div>
      <%end%>
      <div class="row">
        <div class="span1"></div>
        <div class="span10 well">
          <%= yield %>
        </div>
        <div class="span1"></div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->
   at the bottom
  </body>
</html>

app/views/shared/_js_frags.html.erb
<script type='text/x-handlerbars' id='main-header-hbr'>
  <div class='header-container'>
      <div class='submit_story'>submit story</div>
  </div>
</script>


<script type='text/x-handlerbars' id='stories-list-hbr'>
  <div class='day-container'>
 {{date}}<br />
  {{#each stories}}
      <div>
        <a href='{{headline}}'>{{headline}}</a>
        <div class='show-comments' data-story-id='{{id}}'>comments</div><div class='show_comments'>7 comments</div>
      </div>
  {{/each}}
  </div>
</script>

app/views/welcome/index.html.erb
<%=render 'shared/js_frags' %>

<h1>Welcome to our App</h1>


<% unless current_user %>
<div class="center">
  <%= link_to "Login with Instagram", authenticate_path, class: 'btn btn-primary btn-large' %>
</div>
<% else %>

show image here:

<%=image_tag session[:user_image] %>

here i am!

<table>
    <thead>
        <tr>
            <td>Name :: </td>
            <td> <%= current_user.full_name %></td>
        </tr>
        <tr>
            <td>User Name :: </td>
            <td> <%= current_user.user_name %></td>
        </tr>

        <tr>
            <td>Access Token :: </td>
            <td> <%= current_user.auth_token %></td>
        </tr>


        <tr>
            <td>Instagram Id :: </td>
            <td> <%= current_user.instagram_id %></td>
        </tr>


    </thead>
</table>


<% end %>

<div class='main-header'></div>
<div class='stories-list'></div>